### ISSUE TITLE
How to get Facial Action Unit with OpenFace?

### ISSUE THREAD

**Issue by ZackyCaleb** [Wolfsin/Au-Classify-Base-On-UTA_RLDD#1]
Thanks for your sharing.
Would you like to share your operation about getting the Facial Action Unit information?

**Comment by Wolfsin** [comment]
You can use OpenFace Command line. The following is its official description.
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by ZackyCaleb** [comment]
> You can use the OpenFace Command line. The following is its official description. https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments
Thank you. It is highly appreciated. Have you tried using Python and OpenFace to get Facial Action Unit?

**Comment by Wolfsin** [comment]
I also hoped to directly implement the direct call of OpenFace in Python, but OpenFace did not provide a Python interface at that time (2021).
OpenFace provides a code snippet for listening to ZeroMQ streams using Python, but it requires assistance from C#. There is more discussion about the Python interface on the issue page. You can refer to it to see if there are any new developments.

https://github.com/TadasBaltrusaitis/OpenFace/issues/953
https://github.com/TadasBaltrusaitis/OpenFace/issues?q=python

**Comment by ZackyCaleb** [comment]
> I also hoped to directly implement the direct call of OpenFace in Python, but OpenFace did not provide a Python interface at that time (2021). OpenFace provides a code snippet for listening to ZeroMQ streams using Python, but it requires assistance from C#. There is more discussion about the Python interface on the issue page. You can refer to it to see if there are any new developments.
> 
> [TadasBaltrusaitis/OpenFace#953](https://github.com/TadasBaltrusaitis/OpenFace/issues/953) https://github.com/TadasBaltrusaitis/OpenFace/issues?q=python
Thank you! I got it.
